# Generated by Django 5.0.2 on 2024-03-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Profile', '0002_alter_myuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
